const producten = [
    {
        id: 0,
        name: "Blue T-shirt",
        prijs: 15.90,
        instock: 5,
        imgSrc: "images/items/12.jpg",
    },
    {
        id: 1,
        name: "Winter Jacket",
        prijs: 72.90,
        instock: 10,
        imgSrc: "images/items/11.jpg",
    },
    {
        id: 2,
        name: "Mens T-shirt",
        prijs: 29.98,
        instock: 10,
        imgSrc: "images/items/10.jpg",
    },
    {
        id: 3,
        name: "Shorts Jeans",
        prijs: 75.50,
        instock: 20,
        imgSrc: "images/items/9.jpg",
    },
    {
        id: 4,
        name: "Apple Watch",
        prijs: 75.50,
        instock: 4,
        imgSrc: "images/items/5.jpg",
    },
    {
        id: 5,
        name: "Watch",
        prijs: 99.50,
        instock: 1,
        imgSrc: "images/items/6.jpg",
    },
    {
        id: 6,
        name: "Gaming Headset",
        prijs: 41.50,
        instock: 3,
        imgSrc: "images/items/7.jpg",
    },
    {
        id: 7,
        name: "Bag",
        prijs: 75.50,
        instock: 5,
        imgSrc: "images/items/8.jpg",
    },
]